development:
  adapter: redis
  url: redis://localhost:6379/1

test:
  adapter: async

production:
  adapter: redis
  url: redis://rediscloud:CWCmHZKQTvDaguoO@pub-redis-14360.eu-west-1-1.1.ec2.garantiadata.com:14360
